export const API_ENDPOINTS = {
    CONFIG: {
        BASE_URL: import.meta.env.VITE_API_BASE_URL,
        PROFILE_IMAGE_URL: import.meta.env.VITE_PROFILE_IMAGE_URL,
        STOCK_IMAGE_URL: import.meta.env.VITE_STOCK_IMAGE_URL,
    },
    MARKET_AI: {
        QUERY: '/ai/market/query',
    },
    STOCKS: {
        BASE: '/stocks',
        ADMIN: '/admin/stocks',
        BULK_UPLOAD: '/admin/stocks/bulk-upload',
        SEARCH: '/stocks/search',
        ADMIN_SEARCH: '/admin/stocks/search',
        BY_SYMBOL: '/admin/stocks/symbol',
        BY_ID_PUBLIC: (id) => `/stocks/${id}`,
        BY_SYMBOL_PUBLIC: (symbol) => `/stocks/symbol/${symbol}`,
        MARKET_GAINERS: '/stocks/market/gainers',
        MARKET_LOSERS: '/stocks/market/losers',
        MARKET_MOST_TRADED: '/stocks/market/most-traded',
        PRICES: {
            LATEST: '/stocks/prices/latest',
            LATEST_BY_ID: (id) => `/stocks/prices/${id}/latest`,
            LATEST_BY_SYMBOL: (symbol) => `/stocks/prices/symbol/${symbol}/latest`,
            HISTORY: (id) => `/stocks/prices/${id}/history`,
            INDICATORS: (id) => `/stocks/prices/${id}/indicators`,
            CHART: (symbol, range) => `/stocks/prices/chart/${symbol}/${range}`,
            YAHOO_LATEST_BY_ID: (id) => `/stocks/prices/${id}/yahoo/latest`,
            YAHOO_HISTORY_BY_ID: (id) => `/stocks/prices/${id}/yahoo/history`,
            YAHOO_CHART_BY_ID: (id) => `/stocks/prices/${id}/yahoo/chart`,
        },
    },
    WATCHLIST: {
        BASE: '/api/watchlists',
        ITEMS: (id) => `/api/watchlists/${id}/items`,
        CONTAINS: (id) => `/api/watchlists/contains/${id}`,
        IDS_CONTAINING: (id) => `/api/watchlists/stock/${id}/watchlist-ids`,
    },
    USER: {
        ME: '/users/me',
        CREATE: '/users/create',
        IMAGE: '/users/me/image',
        KYC: '/users/me/kyc',
        KYC_STATUS: '/users/me/kyc-status',
        PASSWORD: '/users/me/password',
    },
    WALLET: {
        ME: '/wallet/me',
        SEND_OTP: '/wallet/send-otp',
        ADD_FUNDS: '/wallet/add-funds',
        WITHDRAW: '/wallet/withdraw',
        TRANSACTIONS: '/wallet/transactions',
    },
    BANK_ACCOUNT: {
        BASE: '/bank-accounts',
        LINK: '/bank-accounts/link',
        PRIMARY: '/bank-accounts/primary',
        DELETE: (id) => `/bank-accounts/${id}`,
        SET_PRIMARY: (id) => `/bank-accounts/${id}/primary`,
    },
    ORDERS: {
        BASE: '/orders',
        HOLDINGS: '/orders/holdings',
        HOLDING_BY_STOCK: (stockId) => `/orders/holdings/${stockId}`,
        BY_ID: (id) => `/orders/${id}`,
    },
    ALERTS: {
        BASE: '/api/alerts',
        PAGED: '/api/alerts/paged',
        BY_ID: (id) => `/api/alerts/${id}`,
    },
    AUTOSELL: {
        BASE: '/api/autosell',
        PAGED: '/api/autosell/paged',
        BY_ID: (id) => `/api/autosell/${id}`,
    },
    NOTIFICATIONS: {
        BASE: '/api/notifications',
        UNREAD_COUNT: '/api/notifications/unread/count',
        READ: (id) => `/api/notifications/${id}/read`,
        READ_ALL: '/api/notifications/read-all',
        BY_ID: (id) => `/api/notifications/${id}`,
        SOUND_URL: "/notificationSound.mp3",
    },
    ADMIN: {
        USERS: {
            PAGED: '/admin/users/paged',
            BLOCK: (id) => `/admin/users/${id}/block`,
            UNBLOCK: (id) => `/admin/users/${id}/unblock`,
        },
    },
};
